---
title: "Middle-Income Trap"
author: "Siddharth Dixit"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(shiny)
library(dplyr)
library(scales)
library(readxl)
library(shinycssloaders)

wdiApp <- read_excel("wdiApp.xlsx")

wdiApp$country <- as.factor(wdiApp$country)
wdiApp$WB.Region <- as.factor(wdiApp$WB.Region)
wdiApp$Years <- as.integer(wdiApp$Years)
wdiApp$GDP <- as.numeric(wdiApp$GDP)
wdiApp$GNI <- as.numeric(wdiApp$GNI)
wdiApp$POP <- as.numeric(wdiApp$POP)

wdiApp[is.na(wdiApp)] <- 0
```

Input {.sidebar}
-----------------------------------------------------------------------

### Select Input

```{r}
hr()
#select one or more world bank regions
selectizeInput(inputId = "WB",
                     label = "Select one, or more regions:",
                     choices=levels(wdiApp$WB.Region),
                     selected=levels(wdiApp$WB.Region),
                     multiple = TRUE)
hr()
#select one or more countries
selectizeInput(inputId = "nation",
                     label="Choose one, or more countries",
                     choices=wdiApp$country,
                     options = list(placeholder='select a country name'),
                     multiple=TRUE)

 plotdata <- reactive({
    req(input$WB)
    z <- subset(wdiApp, WB.Region %in% input$WB)
    return(z)
  })
 
 observeEvent(input$nation,{
    reactivestatement2 <- reactive({
      req(input$nation)
      z <- subset(wdiApp, country %in% input$nation)
      return(z)
    })
 }
 )
```

The size of each point represents the total population during that year.

The World Bank determines the threshold for classification of countries by Gross National Income per capita. New thresholds are determined at the start of the Bank’s fiscal year in July and remain fixed for twelve months regardless of subsequent revisions to estimates.
Low Income: below $995,
Lower Middle Income: $996 to $3,895,
Upper Middle Income: $3,896 to $12,055,
High Income: above $12,055,

Note:
1. The waving bars, on the right, show that the data is loading. The plot will take a little while to load as you increase the selection/changes for countries or regions.
2. The data is sourced from World Bank's World Development Indicators (WDI). However, many countries don't have GDP and/or GNI data for every year. Therefore, each country enters the animation in the year, from the upper left corner, from which its data becomes available.


Columns {data-width=450}
-----------------------------------------------------------------------

### Middle-Income Trap

```{r}
renderPlotly({
    ggplotly(ggplot(data = plotdata(), mapping = aes(x=GNI, y=GDP/1000000000, color=WB.Region))+
               geom_vline(xintercept = c(995, 3895, 12055), size=0.3, color="yellow")+
               geom_point(aes(size=POP,frame=Years, ids=country), alpha=0.7) +
               scale_x_log10(breaks=c(995,3895, 12055), labels=comma)+scale_y_log10(labels=comma)+
               labs(x="GNI per capita, (current US$)", y="GDP (constant 2010 US$), in billions", color="World Bank Regions")+
               guides(size=FALSE)+
               theme_bw())
})

renderPlotly({
      ggplotly(ggplot(data = plotdata(),mapping = aes(x=GNI, y=GDP/1000000000, color=WB.Region))+
                 geom_text(data = reactivestatement2(), aes(label=country,frame=Years, ids=country), nudge_x = 0, nudge_y = 0.3)+
                 geom_point(data = reactivestatement2(),aes(size=POP,frame=Years, ids=country, color=WB.Region))+
                 
                 geom_point(aes(size=POP,frame=Years, ids=country, color=WB.Region), alpha=0.2) +
                 geom_vline(xintercept = c(995, 3895, 12055), size=0.3, color="yellow")+
                 
                 scale_x_log10(breaks=c(995,3895, 12055), labels=comma)+scale_y_log10(labels=comma)+
                 labs(x="GNI per capita, (current US$)", y="GDP (constant 2010 US$), in billions", color="World Bank Regions")+
                 guides(size=FALSE)+
                 theme_bw())
      
    })

```


